function classes = portableOperatorClasses()
%PORTABLEOPERATORCLASSES Return class names supported by the parser contract.

classes = { ...
    'nirs4all.operators.splitters.KennardStoneSplitter', ...
    'nirs4all.operators.splitters.splitters.KennardStoneSplitter', ...
    'n4m.KennardStone', ...
    'nirs4all.operators.transforms.SNV', ...
    'nirs4all.operators.transforms.StandardNormalVariate', ...
    'nirs4all.operators.transforms.scalers.StandardNormalVariate', ...
    'n4m.SNV', ...
    'nirs4all.operators.transforms.SavitzkyGolay', ...
    'nirs4all.operators.transforms.nirs.SavitzkyGolay', ...
    'n4m.SavitzkyGolay', ...
    'sklearn.cross_decomposition.PLSRegression', ...
    'sklearn.cross_decomposition._pls.PLSRegression', ...
    'n4m.PLS', ...
    'n4m.PLSRegression' ...
};
end
